### ISSUE TITLE
Content ideas...

### ISSUE THREAD

**Issue by thisIsTheFoxe** [thisIsTheFoxe/DHBW-Swift-Lecture#1]
Think about what "App" we want to show in AR.
Meaning, what should actually be displayed on the ViewController-Plane in AR?

**Comment by thisIsTheFoxe** [comment]
Idea: HomepwnAR
Use the Homepwner project as base.. and customize it with different colors / UI-stuff and different Items.
Also maybe spawn different 3D items in AR when user has tapped one.... [#3, #4, #5]

**Comment by inf17000** [comment]
Compare #4

**Comment by thisIsTheFoxe** [comment]
There's no more time now to choose a different idea...
