### ISSUE TITLE
Create Base Project

### ISSUE THREAD

**Issue by thisIsTheFoxe** [thisIsTheFoxe/DHBW-Swift-Lecture#4]
Different colors / shapes, maybe even completly different UIElemets?
Also customize the different objects one can create (to objects one can "easily" create / find 3D obejcts for")

**Comment by inf17000** [comment]
Use simple Color-Piker instead of Homepwner.

If it´s possible to easily change the color of 3D-Objects...

**Comment by inf17000** [comment]
**Option 1**
Show just some chosen colors. The user is able to select one of those.
![Chameleon-Global-650x482](https://user-images.githubusercontent.com/49722383/58466505-0e544200-813a-11e9-92da-435d6d84ead7.png)

**Comment by inf17000** [comment]
**Option 2**
Show color-wheel to select any color possible.
![screen-shot-1](https://user-images.githubusercontent.com/49722383/58466638-54110a80-813a-11e9-9efa-6001ab996ab3.png)

**Comment by thisIsTheFoxe** [comment]
due to time reasons imo it'd probably be easier and faster to just use some nice 

> chosen colors

.

**Comment by inf17000** [comment]
Create nice Color Palettes:
http://colormind.io
